# Generated by Django 2.1 on 2018-09-04 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('earned_leave', models.IntegerField()),
                ('casual_leave', models.IntegerField()),
                ('sick_leave', models.IntegerField()),
                ('paid_leave', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Python', 'Python'), ('Javascripr', 'Javascript')], max_length=50)),
                ('designation', models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer')], max_length=50)),
                ('type_of_leave', models.CharField(choices=[('Earned Leave', 'Earned Leave'), ('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Paid Leave', 'Paid Leave')], max_length=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reporting_manager', models.CharField(choices=[('0001_manager', '0001_manager'), ('0002_manager', '0002_manager')], max_length=50)),
                ('reason', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('0', 'Rejected'), ('1', 'Accepted')], max_length=15)),
                ('reason_reject', models.CharField(default='-', max_length=50, verbose_name='reason for rejection')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
