# Generated by Django 2.1 on 2018-09-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrequests', '0002_remove_history_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='employee_ID',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
