# Generated by Django 2.1 on 2018-09-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrequests', '0003_history_employee_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': "Employee's Leaves Eligibility", 'verbose_name_plural': "Employee's Leaves Eligibility"},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': 'Leaves Applied', 'verbose_name_plural': 'Leaves Applied'},
        ),
        migrations.AddField(
            model_name='history',
            name='leave',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lrequests.Leave'),
        ),
    ]
