# Generated by Django 2.1 on 2018-09-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrequests', '0004_auto_20180904_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='leave',
        ),
        migrations.AddField(
            model_name='history',
            name='last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
