# Generated by Django 2.1 on 2018-09-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Employee Details', 'verbose_name_plural': 'Employee Details'},
        ),
    ]
